language: php
 
php:

  - 5.6.28

env:
  - SomeTest.php
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit SomeTest.php

matrix:
  allow_failures:
    - php: 5.6.28
  fast_finish: true

notifications:
  on_success: never
  on_failure: always
